import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk, Roboto_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} ${robotoMono.variable} antialiased`}
      >
        <ThemeProvider
          defaultTheme="system"
          storageKey="zoba-theme"
        >
          {children}
          <Toaster
            theme="system"
            position="top-center"
            closeButton
            toastOptions={{
              style: {
                background: 'var(--delft-blue)',
                color: 'var(--ghost-white)',
                border: '1px solid var(--periwinkle)',
                fontWeight: 500,
              },
              duration: 2000,
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
